services:
  api:
    build: ../apps/api
    env_file:
      - ../.env
    environment:
      - "DATABASE_URL=postgresql://marketplace:marketplace@postgres:5432/marketplace?schema=public"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "3000:3000"

  worker:
    build: ../apps/api
    command: ["node", "dist/workers/start.js"]
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api

volumes:
  pgdata:

   